[package]
name = "bitfield-impl"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = {version = "2", features = ["extra-traits", "full"]}
proc-macro2 = "1"
